### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by Daniel-Ric** [tim03we/AdvancedJoin-Nukkit#1]
Please make a JAR Release on GitHub or pull it on NukkitX.com :D

**Comment by tim03we** [comment]
Okay. :D

**Comment by Daniel-Ric** [comment]
And?

**Comment by tim03we** [comment]
I'll make one today at noon.

**Comment by tim03we** [comment]
In the repository you will find the jar file.

**Comment by Daniel-Ric** [comment]
JAR error on github...
